stages:
  - build
  - docker
  - deploy

build:
  stage: build
  image: 'docker.lcgc.work/node-cnpm:10.15.0'
  only:
    - dev
    - pre
    - master
  before_script:
    - export BUILD_PATH=$(pwd)
    - export APP_PATH=/app
  script:
    - rm -rf ${APP_PATH} && cp -r ${BUILD_PATH} ${APP_PATH}
    - cd ${APP_PATH} && cnpm install && cnpm run build && cp -r dist ${BUILD_PATH}
  artifacts:
    name: '${CI_PIPELINE_ID}'
    paths:
      - dist/
    expire_in: 1d
  cache:
    paths:
      - node_modules/

docker:
  stage: docker
  image: 'docker:dind'
  when: on_success
  only:
    - dev
    - pre
    - master
  before_script:
    - export BUILD_PATH=$(pwd)
    - export IMAGE_NAME=docker.lcgc.work/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
  script:
    - docker build -t ${IMAGE_NAME} ${BUILD_PATH}
    - docker push ${IMAGE_NAME}

deploy-dev:
  stage: deploy
  image: 'docker.lcgc.work/kubectl'
  when: on_success
  dependencies: []
  only:
    - dev
  environment:
    name: dev
  before_script:
    - export CIK8S_CONFIG_TARGET=stage
    - export CIK8S_CONFIG_TOKEN=${STAGE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=1
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
    - export CIK8S_ENV_EGG_SERVER_ENV=dev
    - export CIK8S_ENV_PUBLIC_PATH=${PUBLIC_PATH}
    - export CIK8S_RESOURCES_REQUESTS_MEMORY=200Mi
    - export CIK8S_PORT_APP_PORT=
  script:
    - deploy

deploy-pre:
  stage: deploy
  image: 'docker.lcgc.work/kubectl'
  when: on_success
  dependencies: []
  only:
    - pre
  environment:
    name: pre
  before_script:
    - export CIK8S_CONFIG_TARGET=pre
    - export CIK8S_CONFIG_TOKEN=${RELEASE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=1
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
    - export CIK8S_ENV_EGG_SERVER_ENV=pre
    - export CIK8S_ENV_PUBLIC_PATH=${PUBLIC_PATH}
    - export CIK8S_RESOURCES_REQUESTS_MEMORY=200Mi
    - export CIK8S_PORT_APP_PORT=
  script:
    - deploy

deploy-prod:
  stage: deploy
  image: 'docker.lcgc.work/kubectl'
  when: manual
  dependencies: []
  only:
    - master
  environment:
    name: prod
  before_script:
    - export CIK8S_CONFIG_TARGET=release
    - export CIK8S_CONFIG_TOKEN=${RELEASE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=2
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}
    - export CIK8S_ENV_EGG_SERVER_ENV=prod
    - export CIK8S_ENV_PUBLIC_PATH=${PUBLIC_PATH}
    - export CIK8S_RESOURCES_REQUESTS_MEMORY=300Mi
    - export CIK8S_PORT_APP_PORT=
  script:
    - deploy
